// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArnPm-vmMwih0CUnjbwL70xUvI81FPcS8',
    appId: '1:252186651821:web:f467e68e5f36294d972a24',
    messagingSenderId: '252186651821',
    projectId: 'chatapp-7dd0a',
    authDomain: 'chatapp-7dd0a.firebaseapp.com',
    storageBucket: 'chatapp-7dd0a.appspot.com',
    measurementId: 'G-KTPQ6RCJ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBattPm3sp0Zqnq78x9aoEj2gu8BLHkAog',
    appId: '1:252186651821:android:e37f7289090915bd972a24',
    messagingSenderId: '252186651821',
    projectId: 'chatapp-7dd0a',
    storageBucket: 'chatapp-7dd0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9sFXT79HrokYuIH3sgo5EZYKs60CTik',
    appId: '1:252186651821:ios:32139bffeaa580ed972a24',
    messagingSenderId: '252186651821',
    projectId: 'chatapp-7dd0a',
    storageBucket: 'chatapp-7dd0a.appspot.com',
    iosClientId: '252186651821-v0u89it1eaur0g8337i6hil6q1ohn5dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN9sFXT79HrokYuIH3sgo5EZYKs60CTik',
    appId: '1:252186651821:ios:32139bffeaa580ed972a24',
    messagingSenderId: '252186651821',
    projectId: 'chatapp-7dd0a',
    storageBucket: 'chatapp-7dd0a.appspot.com',
    iosClientId: '252186651821-v0u89it1eaur0g8337i6hil6q1ohn5dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
